image: Ubuntu1804

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-ibank.jar -port=7777" -P:profile=test &

build_script:
  - ps: ./gradlew test -Dselenide.headless=true --info

